### ISSUE TITLE
input[type=password]'s height is not equal to input[type=text]

### ISSUE THREAD

**Issue by iamstarkov** [nordnet/nordnet-ui-kit#58] opened 2016-07-12 14:23 UTC
if you have two identical forms and one contains password field, another does not and you want to switch between them this issue is causing glitches

**Comment by bstream** [comment] 2017-04-25 07:49
Closing this as I cannot reproduce. See attached image:

![image](https://cloud.githubusercontent.com/assets/3505504/25374080/66ff7232-299c-11e7-923c-38370f915c9d.png)

**Closed by bstream** 2017-04-25 07:49 UTC
Labels: bug
